apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: /etc/secret/POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: /etc/secret/POSTGRES_PASSWORD
            - name: PGDATA
              value: /etc/secret/PGDATA
          volumeMounts:
            - name: postgres-secret
              mountPath: /etc/secret
              readOnly: true
            - name: postgres-data
              mountPath: /data/db
      nodeSelector:
        kubernetes.io/hostname: lmsdev.shop
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
            items:
              - key: POSTGRES_USER
                path: POSTGRES_USER
                mode: 0444
              - key: POSTGRES_PASSWORD
                path: POSTGRES_PASSWORD
                mode: 0444
              - key: PGDATA
                path: PGDATA
                mode: 0444
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---

