apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: postgres
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-volume
  local:
    path: /mnt/kube-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lmsdev.shop
---

